#!/bin/bash

WAIT_TIME=2  # 设置等待时间为 2 秒

cd ./build/Linux-x86_64-GCC


make clean

# sleep $WAIT_TIME

# make
make ADDITIONAL_OPTS="-DINPUT_SUBNORMAL_CHECK -DIGNORE_SUBNORMAL_OUTPUT"
# make ADDITIONAL_OPTS="-DINPUT_SUBNORMAL_CHECK -DOUTPUT_SUBNORMAL_CHECK -DIGNORE_SUBNORMAL_OUTPUT"